name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: science-ar-app/package-lock.json

      - name: Determine base path
        id: path
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          if [[ "$REPO_NAME" == *.github.io ]]; then
            echo "base_path=" >> $GITHUB_OUTPUT
          else
            echo "base_path=/$REPO_NAME" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        working-directory: science-ar-app
        run: npm install

      - name: Build static export
        working-directory: science-ar-app
        env:
          NEXT_BASE_PATH: ${{ steps.path.outputs.base_path }}
        run: |
          npm run build
          mkdir -p out
          touch out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: science-ar-app/out

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
